# Generated by Django 3.2.15 on 2022-10-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='as', upload_to='pics'),
            preserve_default=False,
        ),
    ]
